### ISSUE TITLE
const errors, cant find clap

### ISSUE THREAD

**Issue by tigrazone** [brochweb/zig-json#1]
![image](https://github.com/user-attachments/assets/4a022ed8-7edd-4446-8bbe-f337a3a5cd31)
after fix errors(change var to const)

![image](https://github.com/user-attachments/assets/99dd71c2-dece-4f71-bb53-632f69a193bf)

I use zig-windows-x86_64-0.14.0-dev.2198+e5f5229fd
How to fix it?

**Comment by AWBroch** [comment]
This project uses modules, so it needs to be built with `zig build`. I’ve brought it up to date with zig 0.13.0, if you want to try it now.

**Comment by tigrazone** [comment]
can it be reworked for 0.14.0?

**Comment by AWBroch** [comment]
Did you try it again? It was set up to work with zig 0.11.0 and now I’ve brought it up to date with zig 0.13.0, which might work with zig 0.14 too

**Comment by tigrazone** [comment]
with 0.14.0 I showed errors

**Comment by tigrazone** [comment]
I make clean clone and try to build and I have new errors with 0.14.0:
```
c:\msys64\home\tigra\zig\zig-json>zig build
c:\msys64\home\tigra\zig\zig-json\build.zig:30:24: error: expected type '*const fn (*Build.Step, Build.Step.MakeOptions) anyerror!void', found '*const fn (*Build.Step, Progress.Node) @typeInfo(@typeInfo(@TypeOf(build.codesign)).@"fn".return_type.?).error_union.error_set!void'
    sign_step.makeFn = codesign;
                       ^~~~~~~~
c:\msys64\home\tigra\zig\zig-json\build.zig:30:24: note: pointer type child 'fn (*Build.Step, Progress.Node) @typeInfo(@typeInfo(@TypeOf(build.codesign)).@"fn".return_type.?).error_union.error_set!void' cannot cast into pointer type child 'fn (*Build.Step, Build.Step.MakeOptions) anyerror!void'
c:\msys64\home\tigra\zig\zig-json\build.zig:30:24: note: parameter 1 'Progress.Node' cannot cast into 'Build.Step.MakeOptions'
C:\inst\zig-windows-x86_64-0.14.0-dev.2198+e5f5229fd\zig-windows-x86_64-0.14.0-dev.2198+e5f5229fd\lib\std\Build\Step.zig:71:25: note: struct declared here
pub const MakeOptions = struct {
                        ^~~~~~
C:\inst\zig-windows-x86_64-0.14.0-dev.2198+e5f5229fd\zig-windows-x86_64-0.14.0-dev.2198+e5f5229fd\lib\std\Progress.zig:80:18: note: struct declared here
pub const Node = struct {
                 ^~~~~~
referenced by:
    runBuild__anon_5045: C:\inst\zig-windows-x86_64-0.14.0-dev.2198+e5f5229fd\zig-windows-x86_64-0.14.0-dev.2198+e5f5229fd\lib\std\Build.zig:2295:33
    main: C:\inst\zig-windows-x86_64-0.14.0-dev.2198+e5f5229fd\zig-windows-x86_64-0.14.0-dev.2198+e5f5229fd\lib\compiler\build_runner.zig:339:29
    4 reference(s) hidden; use '-freference-trace=6' to see all references
C:\inst\zig-windows-x86_64-0.14.0-dev.2198+e5f5229fd\zig-windows-x86_64-0.14.0-dev.2198+e5f5229fd\lib\std\posix.zig:1977:9: error: std.posix.getenv is unavailable for Windows because environment strings are in WTF-16 format. See std.process.getEnvVarOwned for a cross-platform API or std.process.getenvW for a Windows-specific API.
        @compileError("std.posix.getenv is unavailable for Windows because environment strings are in WTF-16 format. See std.process.getEnvVarOwned for a cross-platform API or std.process.getenvW for a Windows-specific API.");
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[7] Compile Build Script
c:\msys64\home\tigra\zig\zig-json>
```

**Comment by AWBroch** [comment]
That build step is only for MacOS, I tried adding a condition to filter it out on Windows, but if that didn’t work you can just comment them out on Windows.

**Comment by tigrazone** [comment]
what to comment? can you make changes?
I'm novice in zig and dont understand well

**Comment by AWBroch** [comment]
I tried adding a condition to filter out that step on Windows. If it still doesn’t work, try commenting out lines 30-34 and 55-63 in `build.zig`.

These lines: 

https://github.com/brochweb/zig-json/blob/bf3fcdec3f5759bc3660871f932ccff86ec8089e/build.zig#L30-L34

https://github.com/brochweb/zig-json/blob/bf3fcdec3f5759bc3660871f932ccff86ec8089e/build.zig#L55-L63

**Comment by tigrazone** [comment]
I also try to comment but error is same
![zig-json1](https://github.com/user-attachments/assets/020f9fac-e793-4b62-b1ad-6403bef967d1)
![zig-json2](https://github.com/user-attachments/assets/be655455-47e8-4d5d-a487-0c8f0981298b)
